name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flake8
        run: |
          python -m pip install flake8

      - name: Run Flake8
        run: |
          flake8 src/app.py

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bandit
        run: |
          python -m pip install bandit

      - name: Run Bandit
        run: |
          bandit -r src/app.py --severity-level high

  docker:
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t billy1204/autonomous .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username billy1204 --password-stdin
          docker push billy1204/autonomous
